from types import SimpleNamespace

import lsst.utils.tests
from lsst.daf.base import PropertyList

from pfs.drp.stella.readLineList import ReadLineListTask
from pfs.drp.stella.tests.utils import runTests
from pfs.drp.stella.synthetic import SyntheticConfig, makeSyntheticDetectorMap

from collections import Counter


display = None


class Line(SimpleNamespace):
    """Struct describing a line in our lineList

    Parameters
    ----------
    wavelength : `float`
        Line wavelength (nm).
    intensity : `float`
        Line intensity (arbitrary units).
    description : `str`
        Line ionic species.
    flag : `int`
        If non-zero, indicates the line should not be used for some reason.
    """
    def __init__(self, wavelength, intensity, description, flag):
        super().__init__(wavelength=wavelength, intensity=intensity, description=description, flag=flag)


class ReadLineListTestCase(lsst.utils.tests.TestCase):
    def setUp(self):
        """Define the lineList"""
        self.contents = [
            Line(123.456, 1000, "NeI", 0),
            Line(456.789, 1000, "NeI", 0),
            Line(567.890, 999, "ArI", 0),
            Line(678.901, 1001, "KrI", 0),
            Line(789.012, 100000, "ArI", 1),  # Flagged
            Line(890.123, 123, 'HgII', 0),
            Line(901.123, 14, 'HgI', 0),
            Line(1023.456, 1000, "NeI", 0),
        ]
        self.config = ReadLineListTask.ConfigClass()
        self.config.restrictByLamps = False

    def makeLineList(self, **kwargs):
        """Generate a lineList from the defined contents

        The lineList is generated by writing it to a file, and then using the
        `ReadLineListTask` to read it in.

        Returns the results of running the `ReadLineListTask`.
        """
        with lsst.utils.tests.getTempFilePath(".txt") as filename:
            with open(filename, "w") as fd:
                fd.write("# This is a fake line list\n")
                for line in self.contents:
                    fd.write(f"{line.wavelength} {line.intensity} {line.description} {line.flag}\n")
            self.config.lineListFiles = [filename]
            task = ReadLineListTask(name="readLineList", config=self.config)
            return task.run(**kwargs)

    def assertLineList(self, lineList, expect):
        """Check that the line list as expected

        Parameters
        ----------
        lineList : iterable of `pfs.drp.stella.ReferenceLineList`
            Line list read with `ReadLineListTask`.
        expect : iterable of `Line`
            Expected lines in the list.
        """
        def orderLineList(lineList):
            return sorted(lineList, key=lambda refLine: refLine.wavelength)

        self.assertEqual(len(lineList), len(expect))
        for ll, ex in zip(orderLineList(lineList),
                          orderLineList(expect)):
            self.assertEqual(ll.wavelength, ex.wavelength)
            self.assertEqual(ll.intensity, ex.intensity)
            self.assertEqual(ll.description, ex.description)

    def testBasic(self):
        """Test that we can read a line list"""
        lineList = self.makeLineList()
        self.assertLineList(lineList, self.contents)

    def testLampsArgon(self):
        """Test that we can select Argon-I lines by lamp"""
        metadata = PropertyList()
        metadata.set("W_AITNEO", 0)  # Neon
        metadata.set("W_AITARG", 1)  # Argon
        metadata.set("W_AITKRY", 0)  # Krypton
        self.config.restrictByLamps = True
        lineList = self.makeLineList(metadata=metadata)
        expect = [ll for ll in self.contents if ll.description == "ArI"]
        assert len(expect) == 2  # Two lines are Argon
        self.assertLineList(lineList, expect)

    def testLampsHgCd(self):
        """Test that we can select Mercury-Cadmium lines by lamp"""
        metadata = PropertyList()
        metadata.set("W_AITNEO", 0)  # Neon
        metadata.set("W_AITARG", 0)  # Argon
        metadata.set("W_AITKRY", 0)  # Krypton
        metadata.set("W_AITHGC", 1)  # Mercury-Cadmium
        self.config.restrictByLamps = True
        lineList = self.makeLineList(metadata=metadata)
        expect = [ll for ll in self.contents if ll.description in ["ArI", "HgI", "HgII"]]
        assert len(expect) == 4  # Two lines are Mercury, two are Argon
        self.assertLineList(lineList, expect)

    def testfilterByLampElements(self):
        """Tests that the correct lines are selected
        for the given line elements,
        even when the element names start with the same characters
        """
        task = ReadLineListTask()
        lines = [
            Line(123.456, 1000, "HI", 0),
            Line(456.789, 1000, "HII", 0),
            Line(567.890, 999, "ArI", 0),
            Line(890.123, 123, 'HgII', 0),
            Line(901.123, 14, 'HgI', 0),
            Line(921.123, 14, 'OH', 0),
            Line(931.123, 14, 'OI', 0),
            Line(941.123, 14, 'Na', 0),
            Line(951.123, 14, 'NI', 0),

        ]

        filteredLines = task.filterByLampElements(lines, ['H'])
        self.assertLineList(filteredLines, lines[0:2])

        filteredLines = task.filterByLampElements(lines, ['HI'])
        self.assertLineList(filteredLines, lines[0:1])

        filteredLines = task.filterByLampElements(lines, ['Hg'])
        self.assertLineList(filteredLines, lines[3:5])

        filteredLines = task.filterByLampElements(lines, ['ArI'])
        self.assertLineList(filteredLines, lines[2:3])

        filteredLines = task.filterByLampElements(lines, ['HgI'])
        self.assertLineList(filteredLines, lines[4:5])

        filteredLines = task.filterByLampElements(lines, ['HgII'])
        self.assertLineList(filteredLines, lines[3:4])

        filteredLines = task.filterByLampElements(lines, ['Hg', 'Ar'])
        self.assertLineList(filteredLines, lines[2:5])

        filteredLines = task.filterByLampElements(lines, ['OH'])
        self.assertLineList(filteredLines, lines[5:6])

        filteredLines = task.filterByLampElements(lines, ['N'])
        self.assertLineList(filteredLines, lines[8:9])

    def testMinIntensity(self):
        """Test that we can select lines by applying minIntensity cut"""
        self.config.minIntensity = 1000
        lineList = self.makeLineList()
        expect = [ll for ll in self.contents if ll.intensity >= self.config.minIntensity]
        assert len(expect) == 5
        self.assertLineList(lineList, expect)

    def testDetectorMap(self):
        """Test that we can get a wavelength-filtered lineList"""
        minWl = 400.0
        maxWl = 950.0
        synth = SyntheticConfig()
        detMap = makeSyntheticDetectorMap(synth, minWl, maxWl)
        lineList = self.makeLineList(detectorMap=detMap)
        expect = [ll for ll in self.contents if ll.wavelength > minWl and ll.wavelength < maxWl]
        for ff in synth.fiberId:
            self.assertLineList(lineList, expect)

    def testDuplicates(self):
        """Tests whether HgAr/HgCd active lamps result in no duplicate lines being retrieved"""
        for lampKeyword in ['W_AITHGA', 'W_AITHGC', 'W_AITARG']:
            header = PropertyList()
            header[lampKeyword] = 1
            lines = ReadLineListTask(name="readLineList").run(metadata=header)
            duplicateLines = [wl for wl, count in Counter(lines.wavelength).items() if count > 1]
            self.assertFalse(duplicateLines, f'For lamp keyword {lampKeyword} '
                                             f'duplicate lines found: {duplicateLines}')


class TestMemory(lsst.utils.tests.MemoryTestCase):
    pass


def setup_module(module):
    lsst.utils.tests.init()


if __name__ == "__main__":
    runTests(globals())
