#!/bin/bash

# On MacOS El Capitan and later we need to pass through the library load path
if [[ $(uname -s) = Darwin* ]]; then
    if [[ -z "$DYLD_LIBRARY_PATH" ]]; then
        export DYLD_LIBRARY_PATH=$LSST_LIBRARY_PATH
    fi
fi

export PFS_DATA_DIR=$HOME/PFS/Data
export whoami=$(whoami)

rm -rf $PFS_DATA_DIR
mkdir -p $PFS_DATA_DIR/CALIB

echo "lsst.obs.pfs.PfsMapper" > $PFS_DATA_DIR/_mapper

ingestImages.py $PFS_DATA_DIR $DRP_STELLA_DATA_DIR/tests/data/raw/*.fits --mode link &&
cp -r $DRP_STELLA_DATA_DIR/tests/data/PFS/pfsState $PFS_DATA_DIR &&

#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

constructBias.py $PFS_DATA_DIR --rerun $whoami/calibs \
                 --id visit=7251..7255 \
                 --calibId arm=r spectrograph=1 \
                 --batch-type none &&
genCalibRegistry.py --root $PFS_DATA_DIR/CALIB --validity 360 &&

constructDark.py $PFS_DATA_DIR --rerun $whoami/calibs \
                 --id visit=7291..7293 \
                 --calibId arm=r spectrograph=1 \
                 --batch-type none &&
genCalibRegistry.py --root $PFS_DATA_DIR/CALIB --validity 360 &&

constructFiberTrace.py $PFS_DATA_DIR --rerun $whoami/calibs \
                 --id visit=104 \
                 --calibId arm=r spectrograph=1 \
                 --batch-type none &&
genCalibRegistry.py --root $PFS_DATA_DIR/CALIB --validity 360 &&

constructFiberFlat.py $PFS_DATA_DIR --rerun $whoami/calibs \
                 --id visit=104..112 \
                 --calibId arm=r spectrograph=1 \
                 --batch-type none &&
genCalibRegistry.py --root $PFS_DATA_DIR/CALIB --validity 360 &&

#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

constructArc.py $PFS_DATA_DIR --rerun $whoami/calibs \
                 --id visit=103 \
                 --calibId arm=r spectrograph=1 \
                 --batch-type none &&
genCalibRegistry.py --root $PFS_DATA_DIR/CALIB --validity 360 &&

reduceArc.py $PFS_DATA_DIR --rerun $whoami/tmp --id visit=103 \
                 --clobber-config
