#!/bin/bash

# On MacOS El Capitan and later we need to pass through the library load path
if [[ $(uname -s) = Darwin* ]]; then
    if [[ -z "$DYLD_LIBRARY_PATH" ]]; then
        export DYLD_LIBRARY_PATH=$LSST_LIBRARY_PATH
    fi
fi

export PFS_DATA_DIR=$HOME/PFS/Data
export whoami=$(whoami)

rm -rf $PFS_DATA_DIR
mkdir -p $PFS_DATA_DIR

echo "lsst.obs.pfs.PfsMapper" > $PFS_DATA_DIR/_mapper

ingestImages.py $PFS_DATA_DIR $DRP_STELLA_DATA_DIR/tests/data/raw/*.fits --mode link &&
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
constructBias.py $PFS_DATA_DIR --calib $PFS_DATA_DIR/XCALIB --rerun $whoami/calib \
                 --id visit=7251..7255 \
                 --batch-type none -j 4 --clobber-versions --clobber-config &&
ingestCalibs.py $PFS_DATA_DIR --output $PFS_DATA_DIR/XCALIB --validity 1800 \
        $PFS_DATA_DIR/rerun/$whoami/calib/BIAS/*.fits --mode move &&

constructDark.py $PFS_DATA_DIR --calib $PFS_DATA_DIR/XCALIB --rerun $whoami/calib \
                 --id visit=7291..7293 \
                 --batch-type none -j 4 --clobber-versions --clobber-config &&
ingestCalibs.py $PFS_DATA_DIR --output $PFS_DATA_DIR/XCALIB --validity 1800 \
        $PFS_DATA_DIR/rerun/$whoami/calib/DARK/*.fits --mode move &&

constructFiberFlat.py $PFS_DATA_DIR --calib $PFS_DATA_DIR/XCALIB --rerun $whoami/calib \
                 --id visit=104..112 \
                 --batch-type none -j 4 --clobber-versions --clobber-config &&
ingestCalibs.py $PFS_DATA_DIR --output $PFS_DATA_DIR/XCALIB --validity 1800 \
        $PFS_DATA_DIR/rerun/$whoami/calib/FLAT/*.fits --mode move &&

constructFiberTrace.py $PFS_DATA_DIR --calib $PFS_DATA_DIR/XCALIB --rerun $whoami/calib \
                 --id visit=104 \
                 --batch-type none -j 4 --clobber-versions --clobber-config &&
ingestCalibs.py $PFS_DATA_DIR --output $PFS_DATA_DIR/XCALIB --validity 1800 \
        $PFS_DATA_DIR/rerun/$whoami/calib/FIBERTRACE/*.fits --mode move &&
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#
# Use our new calibs
#
ln -s $PFS_DATA_DIR/XCALIB $PFS_DATA_DIR/CALIB
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
detrend.py $PFS_DATA_DIR --rerun $whoami/tmp -c isr.doFlat=False --id visit=103 --clobber-versions --clobber-config &&

reduceArc.py $PFS_DATA_DIR --rerun $whoami/tmp --id visit=103 --clobber-versions --clobber-config