from typing import Iterator, List, Optional, overload
import numpy as np
from lsst.afw.image import MaskedImageF
from lsst.daf.base import PropertySet

from .FiberTrace import FiberTrace
from .SpectrumSet import SpectrumSet


class FiberTraceSet:
    @overload
    def __init__(self, reservation: int, metadata: Optional[PropertySet] = None): ...
    @overload
    def __init__(self, fiberTraceSet: "FiberTraceSet", deep: bool = False): ...
    def size(self) -> int: ...
    def get(self, index: int) -> FiberTrace: ...
    def set(self, index: int, trace: FiberTrace) -> None: ...
    def add(self, trace: FiberTrace) -> None: ...
    def getMetadata(self) -> PropertySet: ...
    @property
    def metadata(self) -> PropertySet: ...
    def getInternal(self) -> List[FiberTrace]: ...
    def sortTracesByXCenter(self) -> None: ...
    def extractSpectra(
        self,
        image: MaskedImageF,
        badBitMask: int = 0,
        minFracMask: float = 0.3,
        minFracImage: float = 0.4,
    ) -> SpectrumSet: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> FiberTrace: ...
    def __setitem__(self, index: int, trace: FiberTrace) -> None: ...
    def __iter__(self) -> Iterator[FiberTrace]: ...
