from typing import overload
import numpy as np
from lsst.geom import Point2D
from lsst.afw.image import Image, MaskedImage
from pfs.drp.stella import FiberTrace, FiberTraceSet, SpectrumSet
from pfs.drp.stella.math import NormalizedPolynomial2D

class FiberKernel:
    def __init__(self, kernelHalfWidth: int, kernelOrder: int, xBackgroundSize: int, yBackgroundSize: int) -> None: ...
    @property
    def halfWidth(self) -> int: ...
    @property
    def order(self) -> int: ...
    @property
    def numPoly(self) -> int: ...
    @property
    def numParams(self) -> int: ...
    @property
    def coefficients(self) -> list[float]: ...
    @property
    def polynomials(self) -> list[NormalizedPolynomial2D]: ...
    def getHalfWidth(self) -> int: ...
    def getOrder(self) -> int: ...
    def getNumPoly(self) -> int: ...
    def getNumParams(self) -> int: ...
    def getCoefficients(self) -> list[float]: ...
    def getPolynomials(self) -> list[NormalizedPolynomial2D]: ...
    @overload
    def __call__(self, fiberTrace: FiberTrace) -> FiberTrace: ...
    @overload
    def __call__(self, fiberTraces: FiberTraceSet) -> FiberTraceSet: ...
    @overload
    def evaluate(self, x: float, y: float) -> np.ndarray: ...
    @overload
    def evaluate(self, xy: Point2D) -> np.ndarray: ...


def fitFiberKernel(
    image: MaskedImage,
    fiberTraces: FiberTraceSet,
    badBitMask: int = 0,
    kernelHalfWidth: int = 2,
    kernelOrder: int = 3,
    xBackgroundSize: int = 500,
    yBackgroundSize: int = 500,
    rows: np.ndarray | None = None
) -> tuple[FiberKernel, Image, np.ndarray]: ...
