from typing import overload
import numpy as np
from lsst.geom import Point2D, Extent2I, Box2I
from lsst.afw.image import Image, MaskedImage
from pfs.drp.stella import FiberTrace, FiberTraceSet, SpectrumSet
from pfs.drp.stella.math import NormalizedPolynomial2D

class LinearInterpolationHelper:
    IndexWeightPair = tuple[int, float]
    def __init__(self, x: np.ndarray, length: int) -> None: ...
    def getX(self) -> np.ndarray: ...
    @property
    def x(self) -> np.ndarray: ...
    def getLength(self) -> int: ...
    @property
    def length(self) -> int: ...
    def __call__(self, x: int) -> tuple[IndexWeightPair, IndexWeightPair]: ...

class BaseKernel:
    @property
    def dims(self) -> Extent2I: ...
    @property
    def halfWidth(self) -> int: ...
    @property
    def numParams(self) -> int: ...
    @property
    def values(self) -> list[float]: ...
    def getDims(self) -> Extent2I: ...
    def getHalfWidth(self) -> int: ...
    def getNumParams(self) -> int: ...
    def getValues(self) -> list[float]: ...
    @overload
    def __call__(self, fiberTrace: FiberTrace, bbox: Box2I) -> FiberTrace: ...
    @overload
    def __call__(self, fiberTraces: FiberTraceSet, bbox: Box2I) -> FiberTraceSet: ...
    @overload
    def makeOffsetImages(self, dims: Extent2I) -> np.ndarray: ...
    @overload
    def makeOffsetImages(self, width: int, height: int) -> np.ndarray: ...

class FiberKernel(BaseKernel):
    def __init__(
        self,
        dims: Extent2I,
        kernelHalfWidth: int,
        xNumBlocks: int,
        yNumBlocks: int,
        values: np.ndarray,
    ) -> None: ...
    @property
    def xNumBlocks(self) -> int: ...
    @property
    def yNumBlocks(self) -> int: ...
    def getXNumBlocks(self) -> int: ...
    def getYNumBlocks(self) -> int: ...
    @overload
    def evaluate(self, x: float, y: float) -> np.ndarray: ...
    @overload
    def evaluate(self, xy: Point2D) -> np.ndarray: ...
    def writeFits(self, filename: str) -> None: ...
    @classmethod
    def readFits(cls, filename: str) -> "FiberKernel": ...

@overload
def fitFiberKernel(
    image: MaskedImage,
    fiberTraces: FiberTraceSet,
    badBitMask: int = 0,
    kernelHalfWidth: int = 2,
    xKernelNum: int = 7,
    yKernelNum: int = 7,
    rows: np.ndarray | None = None,
    maxIter: int = 20,
    andersonDepth: int = 5,
    andersonDamping: float = 0.25,
    fluxTol: float = 1.0e-2,
    lsqThreshold: float = 1.0e-16,
) -> FiberKernel: ...
@overload
def fitImageKernel(
    source: MaskedImage,
    target: MaskedImage,
    badBitMask: int = 0,
    kernelHalfWidth: int = 2,
    xKernelNum: int = 7,
    yKernelNum: int = 7,
    xBackgroundNum: int = 9,
    yBackgroundNum: int = 9,
    rows: np.ndarray | None = None,
    lsqThreshold: float = 1.0e-16,
) -> FiberKernel: ...
