from __future__ import annotations
from typing import overload

import numpy as np

from lsst.geom import Point2I, Point2D, Point3D

class Triangle:
    @overload
    def __init__(self, a: Point2D, b: Point2D, c: Point2D): ...
    @overload
    def __init__(self): ...
    def isEmpty(self) -> bool: ...
    def getArea(self) -> float: ...
    def getVertex1(self) -> Point2D: ...
    def getVertex2(self) -> Point2D: ...
    def getVertex3(self) -> Point2D: ...
    def getVertices(self) -> tuple[Point2D, Point2D, Point2D]: ...
    @overload
    def contains(self, x: float, y: float) -> bool: ...
    @overload
    def contains(self, point: Point2D) -> bool: ...
    @overload
    def contains(self, barycentric: Point3D) -> bool: ...
    def getCentroid(self) -> Point2D: ...
    def getBarycentricCoordinates(self, point: Point2D) -> Point3D: ...
    def interpolate(self, barycentric: Point3D) -> Point2D: ...

class GridTree:
    def __init__(self, x: np.ndarray, y: np.ndarray, maxPointsPerLeaf: int): ...
    @overload
    def find(self, x: float, y: float, distance: float = np.inf) -> Point2I: ...
    @overload
    def find(self, point: Point2D, distance: float = np.inf) -> Point2I: ...
    @overload
    def getValue(self, i: int, j: int) -> Point2D: ...
    @overload
    def getValue(self, point: Point2I) -> Point2D: ...
    @overload
    def findTriangle(self, x: float, y: float) -> Triangle: ...
    @overload
    def findTriangle(self, point: Point2D) -> Triangle: ...

class GridTransform:
    def __init__(self, u: np.ndarray, v: np.ndarray, x: np.ndarray, y: np.ndarray): ...
    def getU(self) -> np.ndarray: ...
    def getV(self) -> np.ndarray: ...
    def getX(self) -> np.ndarray: ...
    def getY(self) -> np.ndarray: ...
    def getTree(self) -> GridTree: ...
    def getInverse(self) -> "GridTransform": ...
    @overload
    def __call__(self, u: float, v: float) -> Point2D: ...
    @overload
    def __call__(self, uv: Point2D) -> Point2D: ...
    @overload
    def __call__(self, u: np.ndarray, v: np.ndarray) -> np.ndarray: ...
    @overload
    def calculateXY(self, u: float, v: float) -> Point2D: ...
    @overload
    def calculateXY(self, uv: Point2D) -> Point2D: ...
    @overload
    def calculateXY(self, u: np.ndarray, v: np.ndarray) -> np.ndarray: ...
    @overload
    def calculateX(self, u: float, v: float) -> float: ...
    @overload
    def calculateX(self, u: np.ndarray, v: np.ndarray) -> np.ndarray: ...
    @overload
    def calculateX(self, uv: Point2D) -> float: ...
    @overload
    def calculateY(self, u: float, v: float) -> float: ...
    @overload
    def calculateY(self, u: np.ndarray, v: np.ndarray) -> np.ndarray: ...
    @overload
    def calculateY(self, uv: Point2D) -> float: ...
