from typing import Optional, overload
import numpy as np
from lsst.geom import AffineTransform, Box2D

from .Distortion import Distortion
from .math import NormalizedPolynomial2D


class MosaicPolynomialDistortion(Distortion):
    @overload
    def __init__(self, order: int, range: Box2D, coeff: np.ndarray): ...
    @overload
    def __init__(
        self,
        order: int,
        range: Box2D,
        affineCoeff: np.ndarray,
        xCoeff: np.ndarray,
        yCoeff: np.ndarray,
    ): ...
    @staticmethod
    def fit(
        order: int,
        range: Box2D,
        x: np.ndarray,
        y: np.ndarray,
        xMeas: np.ndarray,
        yMeas: np.ndarray,
        xErr: np.ndarray,
        yErr: np.ndarray,
        threshold: float = 1.0e-6,
        forced: Optional[np.ndarray] = None,
        params: Optional[np.ndarray] = None,
        xTrace: Optional[np.ndarray] = None,
        yTrace: Optional[np.ndarray] = None,
        tracePos: Optional[np.ndarray] = None,
        tracePosErr: Optional[np.ndarray] = None,
        traceSlope: Optional[np.ndarray] = None,
        traceSlopeErr: Optional[np.ndarray] = None,
    ) -> "MosaicPolynomialDistortion": ...
    @staticmethod
    def getNumParametersForOrder(order: int) -> int: ...
    def getOrder(self) -> int: ...
    def getRange(self) -> Box2D: ...
    def getCoefficients(self) -> np.ndarray: ...
    @staticmethod
    def getNumDistortionForOrder(order: int) -> int: ...
    def getNumDistortion(self) -> int: ...
    def getAffineCoefficients(self) -> np.ndarray: ...
    def getXCoefficients(self) -> np.ndarray: ...
    def getYCoefficients(self) -> np.ndarray: ...
    def getAffine(self) -> AffineTransform: ...
    def getXPoly(self) -> NormalizedPolynomial2D: ...
    def getYPoly(self) -> NormalizedPolynomial2D: ...
    @overload
    def getOnRightCcd(self, xx: float) -> bool: ...
    @overload
    def getOnRightCcd(self, xx: np.ndarray) -> np.ndarray: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
