from typing import Optional

from lsst.geom import Box2I
from lsst.afw.image import VisitInfo
from lsst.daf.base import PropertySet

from .DetectorMap import DetectorMap
from .OpticalModel import SlitModel, OpticalModel, DetectorModel
from .math import SplineD

class OpticalModelDetectorMap(DetectorMap):
    def __init__(
        self,
        bbox: Box2I,
        slitModel: SlitModel,
        opticalModel: OpticalModel,
        detectorModel: DetectorModel,
        visitInfo: Optional[VisitInfo] = None,
        metadata: Optional[PropertySet] = None
    ): ...
    def getSlitModel(self) -> SlitModel: ...
    def getOpticalModel(self) -> OpticalModel: ...
    def getDetectorModel(self) -> DetectorModel: ...
    @property
    def slitModel(self) -> SlitModel: ...
    @property
    def opticalModel(self) -> OpticalModel: ...
    @property
    def detectorModel(self) -> DetectorModel: ...
    def getXDetectorSpline(self, fiberId: int) -> SplineD: ...
    def getYDetectorSpline(self, fiberId: int) -> SplineD: ...
    def getWavelengthSpline(self, fiberId: int) -> SplineD: ...
