from __future__ import annotations

from typing import overload
import numpy as np

from lsst.geom import Point2D, AffineTransform, Box2I

from .Distortion import Distortion
from .SplinedDetectorMap import SplinedDetectorMap

class SlitModel:
    @overload
    def __init__(
        self,
        fiberId: np.ndarray,
        fiberPitch: float,
        wavelengthDispersion: float,
        spatialOffsets: np.ndarray,
        spectralOffsets: np.ndarray,
        distortions: list[Distortion] | None = None,
    ) -> None: ...
    @overload
    def __init__(self, source: SplinedDetectorMap, distortions: list[Distortion] | None = None) -> None: ...
    def getFiberId(self) -> np.ndarray: ...
    def getFiberPitch(self) -> float: ...
    def getWavelengthDispersion(self) -> float: ...
    def getSpatialOffsets(self) -> np.ndarray: ...
    def getSpectralOffsets(self) -> np.ndarray: ...
    def getSpatialOffset(self, fiberId: int) -> float: ...
    def getSpectralOffset(self, fiberId: int) -> float: ...
    @overload
    def spectrographToSlit(self, fiberId: int, wavelength: float) -> float: ...
    @overload
    def spectrographToSlit(self, fiberId: np.ndarray, wavelength: np.ndarray) -> np.ndarray: ...

class OpticalModel:
    @overload
    def __init__(
        self,
        slit: SlitModel,
        detector: DetectorModel,
    ) -> None: ...
    @overload
    def __init__(self, source: SplinedDetectorMap, distortions: list[Distortion] | None = None) -> None: ...
    def getSpatial(self) -> np.ndarray: ...
    def getSpectral(self) -> np.ndarray: ...
    def getX(self) -> np.ndarray: ...
    def getY(self) -> np.ndarray: ...
    def getSlitToDetector(self) -> np.ndarray: ...
    def getDetectorToSlit(self) -> np.ndarray: ...
    def getDistortions(self) -> list[Distortion]: ...
    @overload
    def slitToDetector(self, spatial: int, spectral: float) -> Point2D: ...
    @overload
    def slitToDetector(self, spatial: np.ndarray, spectral: np.ndarray) -> np.ndarray: ...
    @overload
    def slitToDetector(self, spatialSpectral: Point2D) -> Point2D: ...
    @overload
    def detectorToSlit(self, x: float, y: float) -> Point2D: ...
    @overload
    def detectorToSlit(self, x: np.ndarray, y: np.ndarray) -> np.ndarray: ...
    @overload
    def detectorToSlit(self, xy: Point2D) -> Point2D: ...

class DetectorModel:
    def __init__(
        self,
        bbox: Box2I,
        isDivided: bool,
        rightCcd: AffineTransform | None = None,
        distortions: list[Distortion] | None = None,
    ) -> None: ...
    def getBBox(self) -> Box2I: ...
    def getIsDivided(self) -> bool: ...
    def getRightCcd(self) -> AffineTransform: ...
    def getDistortions(self) -> list[Distortion]: ...
    @overload
    def detectorToPixels(self, x: float, y: float) -> Point2D: ...
    @overload
    def detectorToPixels(self, x: np.ndarray, y: np.ndarray) -> np.ndarray: ...
    @overload
    def detectorToPixels(self, xy: Point2D) -> Point2D: ...
    @overload
    def pixelsToDetector(self, p: float, q: float) -> Point2D: ...
    @overload
    def pixelsToDetector(self, p: np.ndarray, q: np.ndarray) -> np.ndarray: ...
    @overload
    def pixelsToDetector(self, pq: Point2D) -> Point2D: ...
