from typing import Optional, overload
import numpy as np
from lsst.geom import Box2D

from .Distortion import Distortion
from .math import NormalizedPolynomial2D


class PolynomialDistortion(Distortion):
    @overload
    def __init__(self, distortionOrder: int, range: Box2D, coeff: np.ndarray): ...
    @overload
    def __init__(
        self, distortionOrder: int, range: Box2D, xCoeff: np.ndarray, yCoeff: np.ndarray
    ): ...
    @staticmethod
    def fit(
        distortionOrder: int,
        range: Box2D,
        x: np.ndarray,
        y: np.ndarray,
        xMeas: np.ndarray,
        yMeas: np.ndarray,
        xErr: np.ndarray,
        yErr: np.ndarray,
        isLine: np.ndarray,
        slope: np.ndarray,
        threshold: float = 1.0e-6,
        forced: Optional[np.ndarray] = None,
        params: Optional[np.ndarray] = None,
    ) -> "PolynomialDistortion": ...
    @staticmethod
    def getNumParametersForOrder(distortionOrder: int) -> int: ...
    def getOrder(self) -> int: ...
    def getRange(self) -> Box2D: ...
    def getCoefficients(self) -> np.ndarray: ...
    @staticmethod
    def getNumDistortionForOrder(order: int) -> int: ...
    def getNumDistortion(self) -> int: ...
    def getXCoefficients(self) -> np.ndarray: ...
    def getYCoefficients(self) -> np.ndarray: ...
    def getXPoly(self) -> NormalizedPolynomial2D: ...
    def getYPoly(self) -> NormalizedPolynomial2D: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
