# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(
    ['ReferenceLine',
     'Spectrum',
     'SpectrumSet',
     'controls',
     'FiberTrace',
     'FiberTraceSet',
     'spline',
     'SpectralPsf',
     'NevenPsf',
     'tests/oversampledPsf',
     'tests/nevenPsf',
     'symmetricTridiagonal',
     'fitLine',
     'traces',
     'profile',
     'math',
     'DetectorMap',
     'SplinedDetectorMap',
     'GlobalDetectorModel',
     'DifferentialDetectorMap',
     ],
    addUnderscore=False
)
