# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(
    ['ReferenceLine',
     'Spectrum',
     'SpectrumSet',
     'controls',
     'FiberTrace',
     'FiberTraceSet',
     'detectorMap',
     'spline',
     'SpectralPsf',
     'tests/oversampledPsf',
     ],
    addUnderscore=False
)
