from typing import overload
from lsst.afw.detection import Psf
from lsst.afw.geom.ellipses import Quadrupole
from lsst.afw.image import ImageF
from lsst.afw.math import Kernel
from lsst.geom import Box2I, Extent2I, Point2D

from .DetectorMap import DetectorMap


class SpectralPsf(Psf):
    def getDetectorMap(self) -> DetectorMap: ...
    @property
    def detectorMap(self) -> DetectorMap: ...
    @overload
    def computeImage(self, fiberId: int, wavelength: float) -> ImageF: ...
    @overload
    def computeImage(self, position: Point2D) -> ImageF: ...
    @overload
    def computeKernelImage(self, fiberId: int, wavelength: float) -> ImageF: ...
    @overload
    def computeKernelImage(self, position: Point2D) -> ImageF: ...
    @overload
    def computePeak(self, fiberId: int, wavelength: float) -> float: ...
    @overload
    def computePeak(self, position: Point2D) -> float: ...
    @overload
    def computeApertureFlux(self, radius: float, fiberId: int, wavelength: float) -> float: ...
    @overload
    def computeApertureFlux(self, radius: float, position: Point2D) -> float: ...
    @overload
    def computeShape(self, fiberId: int, wavelength: float) -> Quadrupole: ...
    @overload
    def computeShape(self, position: Point2D) -> Quadrupole: ...
    @overload
    def computeShape(self) -> Quadrupole: ...
    @overload
    def getLocalKernel(self, fiberId: int, wavelength: float) -> Kernel: ...
    @overload
    def getLocalKernel(self, position: Point2D) -> Kernel: ...
    @overload
    def computeBBox(self, fiberId: int, wavelength: float) -> Box2I: ...
    @overload
    def computeBBox(self, position: Point2D) -> Box2I: ...


class OversampledPsf(Psf):
    def getOversampleFactor(self) -> int: ...
    @property
    def oversampleFactor(self) -> int: ...
    def getTargetSize(self) -> Extent2I: ...
    @property
    def targetSize(self) -> Extent2I: ...


class ImagingSpectralPsf(SpectralPsf):
    def __init__(self, psf: Psf, detectorMap: DetectorMap): ...
    def getBase(self) -> Psf: ...
    @property
    def imagePsf(self) -> Psf: ...


def resampleKernelImage(
    image: ImageF,
    binning: int,
    bbox: Box2I,
    center: Point2D = ...,
) -> ImageF: ...
def recenterOversampledKernelImage(
    image: ImageF,
    binning: int,
    center: Point2D = ...,
) -> ImageF: ...
