#!/usr/bin/env python

from argparse import ArgumentParser
from pfs.drp.stella.gen3 import butlerImport


def main():
    parser = ArgumentParser(description="Import datasets from 'butler export-calibs' output")
    parser.add_argument("repo", help="Path to the repository")
    parser.add_argument("directory", help="Directory containing the exported datasets")
    parser.add_argument(
        "--export-file",
        help=(
            "Path to the export file (YAML) generated by 'butler export-calibs'; "
            "defaults to 'export.yaml' in the given directory"
        ),
    )
    parser.add_argument(
        "--transfer",
        default="copy",
        help=(
            "Transfer mode to use for ingest. If not None, must be one of "
            "'auto', 'move', 'copy', 'direct', 'split', 'hardlink', 'relsymlink' or 'symlink'."
        ),
    )
    parser.add_argument(
        "--clobber",
        action="store_true",
        help="Clobber existing datasets with the same UUID?",
    )
    parser.add_argument(
        "--debugger", default=False, action="store_true", help="Drop into debugger on import error?"
    )

    args = parser.parse_args()
    return butlerImport(
        args.repo,
        args.directory,
        exportFile=args.export_file,
        transfer=args.transfer,
        clobber=args.clobber,
        debugger=args.debugger,
    )


if __name__ == "__main__":
    main()
